language: csharp
solution: Sluggy.sln
dist: xenial
sudo: required
mono: none
dotnet: 3.1
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test Sluggy.Tests/Sluggy.Tests.csproj
  - dotnet test SluggyUnidecode.Tests/SluggyUnidecode.Tests.csproj