name: Build and Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test Sluggy
      run: dotnet test Sluggy.Tests/Sluggy.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --no-restore

    - name: Test SluggyUnidecode
      run: dotnet test SluggyUnidecode.Tests/SluggyUnidecode.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --no-restore

    - name: Coverage (Codecov)
      uses: codecov/codecov-action@v1.2.1

    - name: Get All Changed Files
      id: files
      uses: jitterbit/get-changed-files@v1

    - name: Run C# Code Analyzer on Sluggy
      uses: microsoft/CSharpCodeAnalyzer@v0.2
      id: analyseSluggy
      with:
        binary-path: 'Sluggy'
        report-on-files: ${{ steps.files.outputs.all }}
    - name: C# Code Analyzer analysis results - Sluggy
      run: echo "${{ steps.analyseSluggy.outputs.results }}"

    - name: Run C# Code Analyzer on SluggyUnidecode
      uses: microsoft/CSharpCodeAnalyzer@v0.2
      id: analyseSluggyUnidecode
      with:
        binary-path: 'SluggyUnidecode'
        report-on-files: ${{ steps.files.outputs.all }}
    - name: C# Code Analyzer analysis results - SluggyUnidecode
      run: echo "${{ steps.analyseSluggyUnidecode.outputs.results }}"
