name: Latest

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test Sluggy
      run: dotnet test Sluggy.Tests/Sluggy.Tests.csproj --no-restore
    - name: Test SluggyUnidecode
      run: dotnet test SluggyUnidecode.Tests/SluggyUnidecode.Tests.csproj --no-restore

    # QUARANTINE
    # - name: C# Code Analyzer
    #   uses: microsoft/CSharpCodeAnalyzer@v0.1-beta

    - name: Coverage (Codecov)
      uses: codecov/codecov-action@v1.0.10

    - name: Generate nuget package Sluggy
      run: dotnet pack --configuration Release -o nupkg
      working-directory: ./Sluggy/
    - name: Publish nuget package
      run: find . -name *.nupkg -type f -print0 | xargs -0 -I pkg dotnet nuget push pkg -k $nuget_api_key -s "https://api.nuget.org/v3/index.json" --skip-duplicate
      env:
        nuget_api_key: ${{ secrets.NUGET_API_KEY }}
      working-directory: ./Sluggy/nupkg

    - name: Generate nuget package SluggyUnidecode
      run: dotnet pack --configuration Release -o nupkg
      working-directory: ./SluggyUnidecode/
    - name: Publish nuget package
      run: find . -name *.nupkg -type f -print0 | xargs -0 -I pkg dotnet nuget push pkg -k $nuget_api_key -s "https://api.nuget.org/v3/index.json" --skip-duplicate
      env:
        nuget_api_key: ${{ secrets.NUGET_API_KEY }}
      working-directory: ./SluggyUnidecode/nupkg
