name: Latest

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.0.0
      with:
        dotnet-version: 3.1.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test Sluggy
      run: dotnet test Sluggy.Tests/Sluggy.Tests.csproj --no-restore
    - name: Test SluggyUnidecode
      run: dotnet test SluggyUnidecode.Tests/SluggyUnidecode.Tests.csproj --no-restore

    - name: Coverage (Codecov)
      uses: codecov/codecov-action@v2.1.0

    - name: Get All Changed Files
      id: files
      uses: jitterbit/get-changed-files@v1

    - name: Run C# Code Analyzer on Sluggy
      uses: microsoft/CSharpCodeAnalyzer@v1.2
      id: analyseSluggy
      with:
        binary-path: 'Sluggy'
        report-on-files: ${{ steps.files.outputs.all }}
    - name: C# Code Analyzer analysis results - Sluggy
      run: echo "${{ steps.analyseSluggy.outputs.results }}"

    - name: Run C# Code Analyzer on SluggyUnidecode
      uses: microsoft/CSharpCodeAnalyzer@v1.2
      id: analyseSluggyUnidecode
      with:
        binary-path: 'SluggyUnidecode'
        report-on-files: ${{ steps.files.outputs.all }}
    - name: C# Code Analyzer analysis results - SluggyUnidecode
      run: echo "${{ steps.analyseSluggyUnidecode.outputs.results }}"

    - name: Generate nuget package Sluggy
      run: dotnet pack --configuration Release -o nupkg
      working-directory: ./Sluggy/
    - name: Publish nuget package
      run: find . -name *.nupkg -type f -print0 | xargs -0 -I pkg dotnet nuget push pkg -k $nuget_api_key -s "https://api.nuget.org/v3/index.json" --skip-duplicate
      env:
        nuget_api_key: ${{ secrets.NUGET_API_KEY }}
      working-directory: ./Sluggy/nupkg

    - name: Generate nuget package SluggyUnidecode
      run: dotnet pack --configuration Release -o nupkg
      working-directory: ./SluggyUnidecode/
    - name: Publish nuget package
      run: find . -name *.nupkg -type f -print0 | xargs -0 -I pkg dotnet nuget push pkg -k $nuget_api_key -s "https://api.nuget.org/v3/index.json" --skip-duplicate
      env:
        nuget_api_key: ${{ secrets.NUGET_API_KEY }}
      working-directory: ./SluggyUnidecode/nupkg
