name: Lint Code Base
on:
  push:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}